# Generated by Django 3.2.10 on 2021-12-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=200)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
